// <auto-generated />
using System;
using DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260228093138_add_datetime_job")]
    partial class add_datetime_job
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaMax_Blob")
                        .HasColumnType("longtext");

                    b.Property<string>("AreaMax_RGB")
                        .HasColumnType("longtext");

                    b.Property<string>("AreaMin_Blob")
                        .HasColumnType("longtext");

                    b.Property<string>("AreaMin_RGB")
                        .HasColumnType("longtext");

                    b.Property<string>("BMax")
                        .HasColumnType("longtext");

                    b.Property<string>("BMin")
                        .HasColumnType("longtext");

                    b.Property<string>("BlobNum")
                        .HasColumnType("longtext");

                    b.Property<string>("BlobNum_KBBL")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EnableMeanScale")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableRGBScaleDif")
                        .HasColumnType("longtext");

                    b.Property<string>("GMax")
                        .HasColumnType("longtext");

                    b.Property<string>("GMin")
                        .HasColumnType("longtext");

                    b.Property<string>("Height")
                        .HasColumnType("longtext");

                    b.Property<string>("HolesAreaMax_RGB")
                        .HasColumnType("longtext");

                    b.Property<string>("HolesAreaMin_RGB")
                        .HasColumnType("longtext");

                    b.Property<string>("IsFlicker")
                        .HasColumnType("longtext");

                    b.Property<string>("IsKBLightTest")
                        .HasColumnType("longtext");

                    b.Property<int>("LedStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Left")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("RGBScaleDif")
                        .HasColumnType("longtext");

                    b.Property<string>("RMax")
                        .HasColumnType("longtext");

                    b.Property<string>("RMin")
                        .HasColumnType("longtext");

                    b.Property<string>("ThresholdMax")
                        .HasColumnType("longtext");

                    b.Property<string>("ThresholdMax_KBBL")
                        .HasColumnType("longtext");

                    b.Property<string>("ThresholdMin")
                        .HasColumnType("longtext");

                    b.Property<string>("ThresholdMin_KBBL")
                        .HasColumnType("longtext");

                    b.Property<string>("Top")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<string>("Width")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LedStatusId");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LED", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.ToTable("LEDs");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LedCamera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LedModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LedModelId");

                    b.ToTable("LedCamera");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LedModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FP")
                        .HasColumnType("longtext");

                    b.Property<string>("KB")
                        .HasColumnType("longtext");

                    b.Property<int>("LedId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LedId");

                    b.ToTable("LedModel");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LedModelConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Delay_Audio")
                        .HasColumnType("longtext");

                    b.Property<string>("Delay_FPTest")
                        .HasColumnType("longtext");

                    b.Property<string>("Delay_FPTime")
                        .HasColumnType("longtext");

                    b.Property<string>("Delay_GetSPKResult")
                        .HasColumnType("longtext");

                    b.Property<string>("Delay_IRTest")
                        .HasColumnType("longtext");

                    b.Property<string>("Delay_Status1")
                        .HasColumnType("longtext");

                    b.Property<string>("Delay_Status2")
                        .HasColumnType("longtext");

                    b.Property<string>("Delay_Status3")
                        .HasColumnType("longtext");

                    b.Property<string>("Delay_Status4")
                        .HasColumnType("longtext");

                    b.Property<string>("Delay_Status5")
                        .HasColumnType("longtext");

                    b.Property<string>("Delay_StatusButtonTime")
                        .HasColumnType("longtext");

                    b.Property<string>("Delay_WriteSNToAudio")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableAudioTest")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableFPTestStatus1")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableFPTestStatus2")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableFPTestStatus3")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableFPTestStatus4")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableFPTestStatus5")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableLedTest1")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableLedTest2")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableLedTest3")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableLedTest4")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableLedTest5")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableSaveSourcePic")
                        .HasColumnType("longtext");

                    b.Property<string>("EndPosX")
                        .HasColumnType("longtext");

                    b.Property<string>("EndPosY")
                        .HasColumnType("longtext");

                    b.Property<string>("EndPosZ")
                        .HasColumnType("longtext");

                    b.Property<string>("FPPositionX")
                        .HasColumnType("longtext");

                    b.Property<string>("FPPositionY")
                        .HasColumnType("longtext");

                    b.Property<string>("FPPositionZ")
                        .HasColumnType("longtext");

                    b.Property<string>("KBSafeZ")
                        .HasColumnType("longtext");

                    b.Property<int>("LedModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PressedKB")
                        .HasColumnType("longtext");

                    b.Property<string>("ReadSPKResultStatus1")
                        .HasColumnType("longtext");

                    b.Property<string>("ReadSPKResultStatus2")
                        .HasColumnType("longtext");

                    b.Property<string>("ReadSPKResultStatus3")
                        .HasColumnType("longtext");

                    b.Property<string>("ReadSPKResultStatus4")
                        .HasColumnType("longtext");

                    b.Property<string>("ReadSPKResultStatus5")
                        .HasColumnType("longtext");

                    b.Property<string>("SKPTestPositionEnable")
                        .HasColumnType("longtext");

                    b.Property<string>("SPKTestPositionX")
                        .HasColumnType("longtext");

                    b.Property<string>("SPKTestPositionY")
                        .HasColumnType("longtext");

                    b.Property<string>("SPKTestPositionZ")
                        .HasColumnType("longtext");

                    b.Property<string>("SPKTestStatus1")
                        .HasColumnType("longtext");

                    b.Property<string>("SPKTestStatus2")
                        .HasColumnType("longtext");

                    b.Property<string>("SPKTestStatus3")
                        .HasColumnType("longtext");

                    b.Property<string>("SPKTestStatus4")
                        .HasColumnType("longtext");

                    b.Property<string>("SPKTestStatus5")
                        .HasColumnType("longtext");

                    b.Property<string>("Status12PosX")
                        .HasColumnType("longtext");

                    b.Property<string>("Status12PosY")
                        .HasColumnType("longtext");

                    b.Property<string>("Status12PosZ")
                        .HasColumnType("longtext");

                    b.Property<string>("Status23PosX")
                        .HasColumnType("longtext");

                    b.Property<string>("Status23PosY")
                        .HasColumnType("longtext");

                    b.Property<string>("Status23PosZ")
                        .HasColumnType("longtext");

                    b.Property<string>("Status34PosX")
                        .HasColumnType("longtext");

                    b.Property<string>("Status34PosY")
                        .HasColumnType("longtext");

                    b.Property<string>("Status34PosZ")
                        .HasColumnType("longtext");

                    b.Property<string>("Status45PosX")
                        .HasColumnType("longtext");

                    b.Property<string>("Status45PosY")
                        .HasColumnType("longtext");

                    b.Property<string>("Status45PosZ")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LedModelId");

                    b.ToTable("LedModelConfig");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LedStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LedCameraId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LedCameraId");

                    b.ToTable("LedStatus");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Line");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Job", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.LedStatus", null)
                        .WithMany("Jobs")
                        .HasForeignKey("LedStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LED", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Line", null)
                        .WithMany("Leds")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LedCamera", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.LedModel", null)
                        .WithMany("Cameras")
                        .HasForeignKey("LedModelId");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LedModel", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.LED", null)
                        .WithMany("LedModels")
                        .HasForeignKey("LedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LedModelConfig", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.LedModel", null)
                        .WithMany("LEDModelConfigs")
                        .HasForeignKey("LedModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LedStatus", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.LedCamera", null)
                        .WithMany("LedStatuses")
                        .HasForeignKey("LedCameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LED", b =>
                {
                    b.Navigation("LedModels");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LedCamera", b =>
                {
                    b.Navigation("LedStatuses");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LedModel", b =>
                {
                    b.Navigation("Cameras");

                    b.Navigation("LEDModelConfigs");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LedStatus", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Line", b =>
                {
                    b.Navigation("Leds");
                });
#pragma warning restore 612, 618
        }
    }
}
