// <auto-generated />
using System;
using DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260327031400_ini")]
    partial class ini
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Entities.LED.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaMax_Blob")
                        .HasColumnType("longtext");

                    b.Property<string>("AreaMax_RGB")
                        .HasColumnType("longtext");

                    b.Property<string>("AreaMin_Blob")
                        .HasColumnType("longtext");

                    b.Property<string>("AreaMin_RGB")
                        .HasColumnType("longtext");

                    b.Property<string>("BMax")
                        .HasColumnType("longtext");

                    b.Property<string>("BMin")
                        .HasColumnType("longtext");

                    b.Property<string>("BlobNum")
                        .HasColumnType("longtext");

                    b.Property<string>("BlobNum_KBBL")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EnableMeanScale")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableRGBScaleDif")
                        .HasColumnType("longtext");

                    b.Property<string>("GMax")
                        .HasColumnType("longtext");

                    b.Property<string>("GMin")
                        .HasColumnType("longtext");

                    b.Property<string>("Height")
                        .HasColumnType("longtext");

                    b.Property<string>("HolesAreaMax_RGB")
                        .HasColumnType("longtext");

                    b.Property<string>("HolesAreaMin_RGB")
                        .HasColumnType("longtext");

                    b.Property<string>("IsFlicker")
                        .HasColumnType("longtext");

                    b.Property<string>("IsKBLightTest")
                        .HasColumnType("longtext");

                    b.Property<int>("LedStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Left")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("RGBScaleDif")
                        .HasColumnType("longtext");

                    b.Property<string>("RMax")
                        .HasColumnType("longtext");

                    b.Property<string>("RMin")
                        .HasColumnType("longtext");

                    b.Property<string>("ThresholdMax")
                        .HasColumnType("longtext");

                    b.Property<string>("ThresholdMax_KBBL")
                        .HasColumnType("longtext");

                    b.Property<string>("ThresholdMin")
                        .HasColumnType("longtext");

                    b.Property<string>("ThresholdMin_KBBL")
                        .HasColumnType("longtext");

                    b.Property<string>("Top")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<string>("Width")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LedStatusId");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LED.LED", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.ToTable("LED");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LED.LedCamera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LedModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LedModelId");

                    b.ToTable("LedCamera");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LED.LedConfig", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Camera1")
                        .HasColumnType("longtext");

                    b.Property<string>("Camera1_Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Camera2")
                        .HasColumnType("longtext");

                    b.Property<string>("Camera2_Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Camera3")
                        .HasColumnType("longtext");

                    b.Property<string>("Camera3_Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Camera4")
                        .HasColumnType("longtext");

                    b.Property<string>("Camera4_Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Camera5")
                        .HasColumnType("longtext");

                    b.Property<string>("Camera5_Status")
                        .HasColumnType("longtext");

                    b.Property<string>("CheckSN")
                        .HasColumnType("longtext");

                    b.Property<string>("Compress")
                        .HasColumnType("longtext");

                    b.Property<string>("CompressLevel")
                        .HasColumnType("longtext");

                    b.Property<string>("Delay_ClearLine")
                        .HasColumnType("longtext");

                    b.Property<string>("Delay_LCDLocation")
                        .HasColumnType("longtext");

                    b.Property<string>("Delay_NBArrived")
                        .HasColumnType("longtext");

                    b.Property<string>("Delay_NBLocation")
                        .HasColumnType("longtext");

                    b.Property<string>("Delay_WaitOut")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableFails")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableMonitorCam1")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableMonitorCam2")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableMonitorCam3")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableMonitorCam4")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableMonitorCam5")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableNGHold")
                        .HasColumnType("longtext");

                    b.Property<string>("Enable_MainBeltWaitManualBelt")
                        .HasColumnType("longtext");

                    b.Property<string>("Enable_RGBButton")
                        .HasColumnType("longtext");

                    b.Property<string>("Fails")
                        .HasColumnType("longtext");

                    b.Property<string>("InfoName_SFCS")
                        .HasColumnType("longtext");

                    b.Property<string>("InfoValue")
                        .HasColumnType("longtext");

                    b.Property<string>("KeyInfoType_SFCS")
                        .HasColumnType("longtext");

                    b.Property<int>("LedId")
                        .HasColumnType("int");

                    b.Property<string>("LeftToRight")
                        .HasColumnType("longtext");

                    b.Property<string>("LineName")
                        .HasColumnType("longtext");

                    b.Property<string>("RegexAudio")
                        .HasColumnType("longtext");

                    b.Property<string>("RegexSN")
                        .HasColumnType("longtext");

                    b.Property<string>("ScanError")
                        .HasColumnType("longtext");

                    b.Property<string>("StageCode_SFCS")
                        .HasColumnType("longtext");

                    b.Property<string>("Timeout_Axis")
                        .HasColumnType("longtext");

                    b.Property<string>("Timeout_Cylinder")
                        .HasColumnType("longtext");

                    b.Property<string>("Timeout_NBArrive")
                        .HasColumnType("longtext");

                    b.Property<string>("Timeout_Scanner")
                        .HasColumnType("longtext");

                    b.Property<string>("Timeout_ScannerConnectSingle")
                        .HasColumnType("longtext");

                    b.Property<string>("Timeout_ScannerConnectTotal")
                        .HasColumnType("longtext");

                    b.Property<string>("UniqueCheck_SFCS")
                        .HasColumnType("longtext");

                    b.Property<string>("WebService_Path")
                        .HasColumnType("longtext");

                    b.Property<string>("X_SaftyPosition")
                        .HasColumnType("longtext");

                    b.Property<string>("Y_SaftyPosition")
                        .HasColumnType("longtext");

                    b.Property<string>("Z_SaftyPosition")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("LedId");

                    b.ToTable("LedConfig");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LED.LedModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FP")
                        .HasColumnType("longtext");

                    b.Property<string>("KB")
                        .HasColumnType("longtext");

                    b.Property<int>("LedId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LedId");

                    b.ToTable("LedModel");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LED.LedModelConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Delay_Audio")
                        .HasColumnType("longtext");

                    b.Property<string>("Delay_FPTest")
                        .HasColumnType("longtext");

                    b.Property<string>("Delay_FPTime")
                        .HasColumnType("longtext");

                    b.Property<string>("Delay_GetSPKResult")
                        .HasColumnType("longtext");

                    b.Property<string>("Delay_IRTest")
                        .HasColumnType("longtext");

                    b.Property<string>("Delay_Status1")
                        .HasColumnType("longtext");

                    b.Property<string>("Delay_Status2")
                        .HasColumnType("longtext");

                    b.Property<string>("Delay_Status3")
                        .HasColumnType("longtext");

                    b.Property<string>("Delay_Status4")
                        .HasColumnType("longtext");

                    b.Property<string>("Delay_Status5")
                        .HasColumnType("longtext");

                    b.Property<string>("Delay_StatusButtonTime")
                        .HasColumnType("longtext");

                    b.Property<string>("Delay_WriteSNToAudio")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableAudioTest")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableFPTestStatus1")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableFPTestStatus2")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableFPTestStatus3")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableFPTestStatus4")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableFPTestStatus5")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableLedTest1")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableLedTest2")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableLedTest3")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableLedTest4")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableLedTest5")
                        .HasColumnType("longtext");

                    b.Property<string>("EnableSaveSourcePic")
                        .HasColumnType("longtext");

                    b.Property<string>("EndPosX")
                        .HasColumnType("longtext");

                    b.Property<string>("EndPosY")
                        .HasColumnType("longtext");

                    b.Property<string>("EndPosZ")
                        .HasColumnType("longtext");

                    b.Property<string>("FPPositionX")
                        .HasColumnType("longtext");

                    b.Property<string>("FPPositionY")
                        .HasColumnType("longtext");

                    b.Property<string>("FPPositionZ")
                        .HasColumnType("longtext");

                    b.Property<string>("KBSafeZ")
                        .HasColumnType("longtext");

                    b.Property<int>("LedModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PressedKB")
                        .HasColumnType("longtext");

                    b.Property<string>("ReadSPKResultStatus1")
                        .HasColumnType("longtext");

                    b.Property<string>("ReadSPKResultStatus2")
                        .HasColumnType("longtext");

                    b.Property<string>("ReadSPKResultStatus3")
                        .HasColumnType("longtext");

                    b.Property<string>("ReadSPKResultStatus4")
                        .HasColumnType("longtext");

                    b.Property<string>("ReadSPKResultStatus5")
                        .HasColumnType("longtext");

                    b.Property<string>("SKPTestPositionEnable")
                        .HasColumnType("longtext");

                    b.Property<string>("SPKTestPositionX")
                        .HasColumnType("longtext");

                    b.Property<string>("SPKTestPositionY")
                        .HasColumnType("longtext");

                    b.Property<string>("SPKTestPositionZ")
                        .HasColumnType("longtext");

                    b.Property<string>("SPKTestStatus1")
                        .HasColumnType("longtext");

                    b.Property<string>("SPKTestStatus2")
                        .HasColumnType("longtext");

                    b.Property<string>("SPKTestStatus3")
                        .HasColumnType("longtext");

                    b.Property<string>("SPKTestStatus4")
                        .HasColumnType("longtext");

                    b.Property<string>("SPKTestStatus5")
                        .HasColumnType("longtext");

                    b.Property<string>("Status12PosX")
                        .HasColumnType("longtext");

                    b.Property<string>("Status12PosY")
                        .HasColumnType("longtext");

                    b.Property<string>("Status12PosZ")
                        .HasColumnType("longtext");

                    b.Property<string>("Status23PosX")
                        .HasColumnType("longtext");

                    b.Property<string>("Status23PosY")
                        .HasColumnType("longtext");

                    b.Property<string>("Status23PosZ")
                        .HasColumnType("longtext");

                    b.Property<string>("Status34PosX")
                        .HasColumnType("longtext");

                    b.Property<string>("Status34PosY")
                        .HasColumnType("longtext");

                    b.Property<string>("Status34PosZ")
                        .HasColumnType("longtext");

                    b.Property<string>("Status45PosX")
                        .HasColumnType("longtext");

                    b.Property<string>("Status45PosY")
                        .HasColumnType("longtext");

                    b.Property<string>("Status45PosZ")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LedModelId");

                    b.ToTable("LedModelConfig");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LED.LedStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LedCameraId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LedCameraId");

                    b.ToTable("LedStatus");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LED.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Line");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LED.Job", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.LED.LedStatus", null)
                        .WithMany("Jobs")
                        .HasForeignKey("LedStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LED.LED", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.LED.Line", null)
                        .WithMany("Leds")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LED.LedCamera", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.LED.LedModel", null)
                        .WithMany("Cameras")
                        .HasForeignKey("LedModelId");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LED.LedConfig", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.LED.LED", null)
                        .WithMany("LedConfigs")
                        .HasForeignKey("LedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LED.LedModel", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.LED.LED", null)
                        .WithMany("LedModels")
                        .HasForeignKey("LedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LED.LedModelConfig", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.LED.LedModel", null)
                        .WithMany("LEDModelConfigs")
                        .HasForeignKey("LedModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LED.LedStatus", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.LED.LedCamera", null)
                        .WithMany("LedStatuses")
                        .HasForeignKey("LedCameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LED.LED", b =>
                {
                    b.Navigation("LedConfigs");

                    b.Navigation("LedModels");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LED.LedCamera", b =>
                {
                    b.Navigation("LedStatuses");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LED.LedModel", b =>
                {
                    b.Navigation("Cameras");

                    b.Navigation("LEDModelConfigs");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LED.LedStatus", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LED.Line", b =>
                {
                    b.Navigation("Leds");
                });
#pragma warning restore 612, 618
        }
    }
}
